### ISSUE TITLE
Not loading

### ISSUE THREAD

**Issue by ghost** [fewfre/FortoresseDressroom#1]
Hello, I'm trying to run dressroom.swf, but it's stuck at:

![image](https://user-images.githubusercontent.com/52384977/154139081-d7c9a36d-73dc-4547-a03a-f1b9d9e5077a.png)

The alternative tools.swf is blank as well.

**Comment by ghost** [comment]
Nevermind, using a browser to run works. A CORS issue?

**Comment by fewfre** [comment]
Hey, so, I remember someone else having this problem, so posting the solution for running it locally using flash player here (or what worked for them at least):

- Open `tools.swf`
- Right click
- Click "Global Settings"
- Click "Advanced" tab
- Click "trusted location settings"
- Add `tools.swf` to it
- Close and reopen

I'm not completely sure why some people can run it locally without issue, but it might be because of some developer setting.

**Comment by ghost** [comment]
Just tried running like you said. In my case going to _Global Settings_ opens an Adobe web link instead, so I basically can't change this setting.

**Comment by fewfre** [comment]
Ugg - it seems you might(?) be able to enable it on [this page](www.macromedia.com/support/flashplayer/sys/settingsmanager.swf), though ironically you'd need flash in the browser to do so >.< (which I don't, so can't test it)

Might just be this feature is disabled now for security reasons - I swear you used to be able to run the fortoresse and tfm swf locally, but it doesn't work for me anymore, and it seems like it might be for the same reason

Well, I'm glad the browsers works for you at least - I'll look into the issue more when I have time, but might be a lost cause
